name: First workflow
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Executing the test job
              run: echo "Executing the test job ..."
            
            - name: checkout repo
              uses: actions/checkout@v4

            - name: Displaying README.md content
              run: cat README.md