name: First workflow
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: Executing the test job
              run: | 
                  echo "Executing  the test job ..."
                  cat README.md