name: Test docker image
on: push
jobs:
  deploy-on-ubuntu:
    stategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: test hello world
        run: docker run hello-world 








# name: Build and deploy
# on: workflow_dispatch
# env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: wissem
#           IMAGE_NAME: app
# jobs: 
#   docker-job:
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Build the image
#         run: echo docker build $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME
        
#       - name: Login
#         run: echo docker login  --username=${{vars.DOCKER_USERNAME}} --password=123456789

#       - name: Push the image
#         run: echo docker run $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME
  
#   deploy-job:
#     concurrency: 
#       group: deploy-to-prod
#       cancel-in-progress: true
#     needs: docker-job
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run the app
#         run: |
#           echo docker run $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME
#           sleep 6000



# name: First workflow
# on: push
# jobs:
#     build-job: 
#         runs-on: ubuntu-latest
#         steps:
#             - name: Build job
#               run: |
#                 sleep 3
#                 echo "building the app..." > app.txt

#             - name: upload the app.txt file
#               uses: actions/upload-artifact@v4
#               with:
#                   name: app-text-file
#                   path: app.txt

#     test-job:
#         needs: build-job
#         runs-on: ubuntu-latest
#         steps:
#             - name: download the app.txt file
#               uses: actions/download-artifact@v5
#               with:
#                   name: app-text-file

#             - name: Testing
#               run: |
#                 sleep 3
#                 cat app.txt
#                 echo "testing the app..."
            
#     deploy-job:
#         needs: test-job
#         runs-on: ubuntu-latest
#         steps: 
#             - name: download the app.txt file
#               uses: actions/download-artifact@v5
#               with:
#                   name: app-text-file

#             - name: Deploy job
#               run: |
#                 sleep 3
#                 cat app.txt
#                 echo "deploying the app..."